# Generated by Django 3.0.8 on 2020-08-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='interval',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
