# Generated by Django 3.0.8 on 2020-08-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0002_auto_20200813_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='end_time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='interval',
            name='start_time',
            field=models.PositiveIntegerField(),
        ),
    ]
